### ISSUE TITLE
QQ

### ISSUE THREAD

**Issue by wangyijin209** [wzk0/app-installation-script#1]
请问这个源里的QQ是基于wine的QQ还是基于deepin-wine的？抑或只是linux-qq？

**Comment by wzk0** [comment]
> 请问这个源里的QQ是基于wine的QQ还是基于deepin-wine的？抑或只是linux-qq？

官方版本的LinuxQQ,这个程序里的脚本没有使用wine容器的

**Comment by wangyijin209** [comment]
好的，谢谢

**Comment by wzk0** [comment]
> 好的，谢谢

这个项目年代久远...我也一直没更新 虽然这个框架可以用 但是一些软件的脚本我没测试过 所以有些软件可以直接看脚本库 https://github.com/wzk0/repo-of-app 单项安装
